# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(editable=False, help_text='формируется автоматически', max_length=30, verbose_name='пользователь')),
                ('header', models.TextField(verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='текст')),
                ('qdate', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Добавить пост блога',
                'verbose_name_plural': '2. Подготовка постов блога',
            },
        ),
        migrations.CreateModel(
            name='ReadUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(editable=False, help_text='формируется автоматически', max_length=30, verbose_name='пользователь')),
                ('signuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='подписанный пользователь')),
            ],
            options={
                'verbose_name': 'Добавить блог пользователя',
                'verbose_name_plural': '1. Блоги пользователей',
            },
        ),
        migrations.AlterIndexTogether(
            name='blogpost',
            index_together=set([('user',)]),
        ),
        migrations.AlterUniqueTogether(
            name='readuser',
            unique_together=set([('user', 'signuser')]),
        ),
        migrations.AlterIndexTogether(
            name='readuser',
            index_together=set([('user', 'signuser')]),
        ),
    ]
