# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(editable=False, help_text='формируется автоматически', max_length=30, verbose_name='пользователь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost', verbose_name='прочитанный пост')),
            ],
            options={
                'verbose_name': 'Прочитанный пост',
                'verbose_name_plural': '3. Прочитанные посты',
            },
        ),
        migrations.AlterIndexTogether(
            name='readpost',
            index_together=set([('user',)]),
        ),
    ]
